apimServiceName: api-ops-prod-eastus

namedValues:
  - name: named-value-1
    properties:
      displayName: "named-value-1"
      keyVault:
        identityClientId: "6f237e57-6314-4c72-8a21-27895ab60a7b"
        secretIdentifier: "https://kv-apiops-prod-eastus.vault.azure.net/secrets/secret-1"
  - name: named-value-2
    properties:
      displayName: "named-value-2"
      keyVault:
        identityClientId: "6f237e57-6314-4c72-8a21-27895ab60a7b"
        secretIdentifier: "https://kv-apiops-prod-eastus.vault.azure.net/secrets/secret-2"
  - name: named-value-3
    properties:
      displayName: "named-value-3"
      keyVault:
        identityClientId: "6f237e57-6314-4c72-8a21-27895ab60a7b"
        secretIdentifier: "https://kv-apiops-prod-eastus.vault.azure.net/secrets/secret-3"
  - name: application-insights-instrumentation-key
    properties:
      displayName: "application-insights-instrumentation-key"
      keyVault:
        identityClientId: "6f237e57-6314-4c72-8a21-27895ab60a7b"
        secretIdentifier: "https://kv-apiops-prod-eastus.vault.azure.net/secrets/application-insights-instrumentation-key"

loggers:
  - name: applicationinsights
    properties:
      loggerType: applicationInsights
      description: prod application insights
      resourceId: "/subscriptions/df7ed44c-e98a-43c4-af18-241e33567262/resourceGroups/RG-UmeshPagar/providers/microsoft.insights/components/appi-apiops-prod-eastus"
      credentials:
        instrumentationKey: "{{application-insights-instrumentation-key}}"
  - name: azuremonitor
    properties:
      loggerType: azureMonitor
      isBuffered: true

diagnostics:
  - name: applicationinsights
    properties:
      verbosity: Error
      loggerId: "/subscriptions/df7ed44c-e98a-43c4-af18-241e33567262/resourceGroups/RG-UmeshPagar/providers/Microsoft.ApiManagement/service/api-ops-prod-eastus/loggers/appi-apiops-prod-eastus"
  - name: azuremonitor
    properties:
      verbosity: Error
      loggerId: "/subscriptions/df7ed44c-e98a-43c4-af18-241e33567262/resourceGroups/RG-UmeshPagar/providers/Microsoft.ApiManagement/service/api-ops-prod-eastus/loggers/azuremonitor"